### ISSUE TITLE
rrInterval bug on HeartRateSerializer

### ISSUE THREAD

**Issue by yosoycody** [kinetic-fit/sensors-swift#5]
While trying to read rrInterval values from the HeartRateService, I noticed that the values are mostly nil. I thought it was my heart rate monitor, but it looks like there's a bug on the HeartRateSerializer. 

This is the current code to read the rrInterval:
`if flags & 0x10 == 0x10 && bytes.count > 6 {
            measurement.rrInterval = UInt16(bytes[index++=]) | UInt16(bytes[index++=]) << 8
        }`

The issue seems to be fixed If I change it to this (removing the count check):
`if flags & 0x10 == 0x10 {
            measurement.rrInterval = UInt16(bytes[index++=]) | UInt16(bytes[index++=]) << 8
        }`

**Comment by netizen01** [comment]
You are correct. I will fix this code.

**Comment by yosoycody** [comment]
Thanks!
